version: '3.8'

services:
  wordpress:
    image: wordpress:6.2
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:latest
    volumes:
      - ./wordpress:/app

volumes:
  db_data:

# .env file
# WORDPRESS_DB_USER=exampleuser
# WORDPRESS_DB_PASSWORD=examplepass
# WORDPRESS_DB_NAME=exampledb
# MYSQL_ROOT_PASSWORD=somewordpress
# MYSQL_DATABASE=exampledb
# MYSQL_USER=exampleuser
# MYSQL_PASSWORD=examplepass
